server:
    port: 8080
eureka:
   client:
      service-url:
       defaultZone: http://localhost:8761/eureka/

spring:
 application:
  name: ApiGateWayForService
 cloud:
    gateway:
      routes:
      - id: Nutritionist_Admin_Service
        uri: http://localhost:8085/
        predicates:
        - Path=/api/v1/**
      - id: Nutritionist_User_Service
        uri: http://localhost:8084/
        predicates:
        - Path=/api/v1/**
      - id: Nutritionist_JWTService
        uri: http://localhost:8081/
        predicates:
        - Path=/api/v1/**
          
      
  